#!/usr/bin/env python3
# 產生 renderer/src/behavior/names_cpp_rust_go.json：C++ 標準函式庫（STL）、Rust、Go 的「呼叫名稱 → 行為分類」名稱表與 API 語意。
# 用法：python scripts/gen-name-tables.py（改了這裡就重跑，再 node scripts/embed-code-ui.js）。
# 名稱的寫法（要跟引擎的呼叫名稱候選一致，見 engine_1_core.js 的 rustCallCandidates／goCallCandidates）：
#   C++  ：呼叫名稱的最後一段（std::sort → sort、v.push_back() → push_back），跟 C 的名稱表合併使用（只對 .cc/.cpp/.cxx/.hpp 檔）。
#   Rust ：路徑呼叫 fs::read_to_string／File::open（完整路徑 std::fs::read_to_string 也會比對到最後兩段）、方法呼叫 .lock、巨集 println!。
#   Go   ：套件函式 os.Open（呼叫端的前綴）、方法 .Lock（任何接收者）、內建 make／append。
# 這些名稱是依官方文件知識整理，沒有逐條對照官方文件；有錯用 behavior_define 修正。
import json, os

def L(s):
    return [x for x in s.split() if x]

C = {}   # category -> {lang: [names]}
def add(cat, lang, names):
    C.setdefault(cat, {}).setdefault(lang, [])
    for n in L(names):
        if n not in C[cat][lang]:
            C[cat][lang].append(n)

# ======================= C++ 標準函式庫（STL） =======================
add('file_io', 'cpp', 'ifstream ofstream fstream wifstream wofstream getline seekg seekp tellg tellp is_open rdbuf ignore peek putback readsome ostream_iterator istream_iterator istreambuf_iterator ostreambuf_iterator')
add('file_io', 'cpp', 'read_file write_file')
add('filesystem_management', 'cpp', 'create_directory create_directories remove_all copy_file copy_symlink create_symlink create_hard_link exists is_directory is_regular_file is_symlink is_empty file_size hard_link_count last_write_time directory_iterator recursive_directory_iterator canonical weakly_canonical absolute relative proximate temp_directory_path current_path permissions space status symlink_status equivalent resize_file')
add('network_io', 'cpp', 'async_connect async_accept async_read async_write async_read_some async_write_some async_resolve async_receive async_send')
add('memory_management', 'cpp', 'make_shared make_unique make_shared_for_overwrite make_unique_for_overwrite allocate_shared allocate deallocate reserve shrink_to_fit use_count owner_before get_deleter pmr_allocate uninitialized_copy uninitialized_fill uninitialized_move uninitialized_default_construct destroy_at destroy_n construct_at aligned_alloc launder addressof assume_aligned')
add('concurrency', 'cpp', 'thread jthread async join detach joinable request_stop stop_requested get_stop_token lock unlock try_lock try_lock_for try_lock_until lock_guard unique_lock scoped_lock shared_lock lock_shared unlock_shared wait wait_for wait_until notify_one notify_all call_once promise set_value set_exception set_value_at_thread_exit get_future packaged_task shared_future atomic_thread_fence atomic_signal_fence fetch_add fetch_sub fetch_and fetch_or fetch_xor compare_exchange_weak compare_exchange_strong atomic_load atomic_store atomic_exchange atomic_fetch_add atomic_fetch_sub test_and_set sleep_for sleep_until yield hardware_concurrency acquire try_acquire release_n arrive arrive_and_wait arrive_and_drop count_down try_wait latch barrier counting_semaphore binary_semaphore this_thread get_id')
add('time_date', 'cpp', 'now duration_cast time_point_cast time_since_epoch to_time_t from_time_t system_clock steady_clock high_resolution_clock utc_clock file_clock floor_duration zoned_time current_zone local_days sys_days year_month_day weekday')
add('string_formatting', 'cpp', 'to_string to_wstring stoi stol stoll stoul stoull stof stod stold to_chars from_chars format vformat format_to format_to_n formatted_size make_format_args getline_str substr c_str stringstream istringstream ostringstream wstringstream str_view string_view setw setprecision setfill setbase hexfloat quoted get_money put_money get_time put_time')
add('logging_output', 'cpp', 'print println vprint vprint_unicode cout cerr clog wcout wcerr')
add('structured_data_parsing', 'cpp', 'regex_match regex_search regex_replace sregex_iterator sregex_token_iterator smatch cmatch basic_regex')
add('nonlocal_control_flow', 'cpp', 'terminate set_terminate get_terminate unexpected current_exception rethrow_exception make_exception_ptr uncaught_exceptions throw_with_nested rethrow_if_nested nested_exception coroutine_handle suspend_always suspend_never co_await co_yield co_return resume')
add('reflection_metaprogramming', 'cpp', 'dynamic_pointer_cast static_pointer_cast const_pointer_cast reinterpret_pointer_cast any_cast get_if holds_alternative visit make_any variant_alternative type_index declval invoke invoke_r apply make_from_tuple bind bind_front mem_fn is_constant_evaluated source_location to_underlying bit_cast')
add('crypto_security', 'cpp', 'random_device mt19937 mt19937_64 minstd_rand default_random_engine uniform_int_distribution uniform_real_distribution normal_distribution bernoulli_distribution seed_seq generate_canonical')
add('arithmetic_logic', 'cpp', 'gcd lcm midpoint lerp popcount countl_zero countl_one countr_zero countr_one rotl rotr bit_width bit_ceil bit_floor has_single_bit byteswap clamp fma hypot cbrt expm1 log1p erf tgamma lgamma beta riemann_zeta comp_ellint_1 assoc_laguerre add_sat sub_sat mul_sat div_sat saturate_cast in_range cmp_equal cmp_less cmp_greater')
add('data_structures_algorithms', 'cpp', 'push_back emplace_back push_front emplace_front pop_back pop_front emplace insert_or_assign try_emplace extract merge_node erase_if resize assign clear lower_bound upper_bound equal_range binary_search sort stable_sort partial_sort partial_sort_copy nth_element is_sorted is_sorted_until sort_heap make_heap push_heap pop_heap is_heap stable_partition partition partition_copy partition_point accumulate reduce transform_reduce inner_product partial_sum inclusive_scan exclusive_scan transform_inclusive_scan adjacent_difference adjacent_find iota min max minmax min_element max_element minmax_element for_each for_each_n transform copy copy_if copy_n copy_backward move_backward fill fill_n generate generate_n remove_if remove_copy remove_copy_if replace replace_if replace_copy unique unique_copy reverse reverse_copy rotate rotate_copy shuffle sample next_permutation prev_permutation is_permutation find_if find_if_not find_end find_first_of search search_n all_of any_of none_of count_if mismatch equal lexicographical_compare includes set_union set_intersection set_difference set_symmetric_difference inplace_merge exchange swap_ranges iter_swap distance advance next prev make_pair make_tuple tie tuple_cat make_optional value_or make_move_iterator back_inserter front_inserter inserter ranges views to_vector span subspan as_bytes as_writable_bytes mdspan stack queue priority_queue')

# ======================= Rust（標準函式庫與常見 crate） =======================
add('file_io', 'rust', 'File::open File::create File::options OpenOptions::new OpenOptions::open fs::read fs::read_to_string fs::write fs::read_dir fs::metadata fs::symlink_metadata fs::canonicalize fs::copy fs::File::open BufReader::new BufWriter::new LineWriter::new .read_to_string .read_to_end .read_line .read_exact .read_buf .lines .bytes .write_all .write_fmt .flush .seek .sync_all .sync_data .set_len .metadata .try_clone io::stdin io::stdout io::stderr io::copy io::read_to_string io::empty io::sink io::repeat tokio::fs::read tokio::fs::write tokio::fs::File::open tokio::fs::read_to_string')
add('filesystem_management', 'rust', 'fs::create_dir fs::create_dir_all fs::remove_file fs::remove_dir fs::remove_dir_all fs::rename fs::hard_link fs::soft_link fs::read_link fs::set_permissions fs::exists Path::new Path::exists Path::is_dir Path::is_file Path::join PathBuf::from PathBuf::new .exists .is_dir .is_file .join .parent .file_name .extension .with_extension .canonicalize .display tempfile::tempdir tempfile::NamedTempFile::new walkdir::WalkDir::new std::env::temp_dir env::temp_dir env::current_dir env::set_current_dir')
add('network_io', 'rust', 'TcpStream::connect TcpStream::connect_timeout TcpListener::bind UdpSocket::bind .accept .incoming .connect .send .send_to .recv .recv_from .peer_addr .local_addr .set_nodelay .set_read_timeout .set_write_timeout .shutdown .set_nonblocking TcpStream::from_std reqwest::get reqwest::Client::new reqwest::blocking::get reqwest::blocking::Client::new .get .post .put .delete .header .json .bearer_auth .send_async hyper::Client::new hyper::Server::bind ureq::get ureq::post ureq::agent surf::get isahc::get tokio::net::TcpStream::connect tokio::net::TcpListener::bind tokio::net::UdpSocket::bind actix_web::HttpServer::new axum::Router::new axum::serve warp::serve tonic::transport::Server::builder tungstenite::connect tokio_tungstenite::connect_async ToSocketAddrs::to_socket_addrs lookup_host')
add('process_exec', 'rust', 'Command::new process::Command::new .arg .args .envs .env .env_clear .current_dir .stdin .stdout .stderr .spawn .output .status .wait .wait_with_output .try_wait .kill .id process::exit process::abort process::id exec::execvp CommandExt::exec duct::cmd xshell::cmd tokio::process::Command::new')
add('env_config_access', 'rust', 'env::var env::var_os env::vars env::vars_os env::args env::args_os env::set_var env::remove_var env::home_dir env::current_exe env::consts env::split_paths env::join_paths dotenv::dotenv dotenvy::dotenv clap::Parser::parse config::Config::builder envy::from_env std::env::var std::env::args env!')
add('logging_output', 'rust', 'println! print! eprintln! eprint! dbg! write! writeln! log::info log::warn log::error log::debug log::trace info! warn! error! debug! trace! tracing::info tracing::warn tracing::error tracing::debug tracing::trace log::log env_logger::init env_logger::builder tracing_subscriber::fmt::init tracing_subscriber::fmt .init')
add('string_formatting', 'rust', 'format! format_args! String::from String::new String::from_utf8 String::from_utf8_lossy String::with_capacity str::from_utf8 str::parse .parse .to_string .to_owned .to_uppercase .to_lowercase .trim .trim_start .trim_end .split .split_whitespace .splitn .rsplit .split_once .rsplit_once .lines .chars .char_indices .contains .starts_with .ends_with .replace .replacen .strip_prefix .strip_suffix .find .rfind .repeat .join .concat .push_str .as_str .into_bytes .escape_debug .eq_ignore_ascii_case char::from_u32 char::from_digit .to_digit .is_alphabetic .is_numeric .is_whitespace u8::from_str_radix i32::from_str_radix i64::from_str_radix u64::from_str_radix f64::from_str FromStr::from_str')
add('structured_data_parsing', 'rust', 'serde_json::from_str serde_json::from_slice serde_json::from_reader serde_json::to_string serde_json::to_string_pretty serde_json::to_vec serde_json::to_writer serde_json::json! serde_json::Value::from json! serde_yaml::from_str serde_yaml::to_string toml::from_str toml::to_string quick_xml::Reader::from_str quick_xml::Writer::new csv::Reader::from_path csv::Reader::from_reader csv::Writer::from_path csv::Writer::from_writer bincode::serialize bincode::deserialize rmp_serde::from_slice ciborium::from_reader prost::Message::decode prost::Message::encode regex::Regex::new Regex::new .is_match .captures .captures_iter .find_iter .replace_all .split_terminator nom::bytes::complete::tag pest::Parser::parse quick_protobuf::deserialize_from_slice')
add('memory_management', 'rust', 'Box::new Box::from_raw Box::into_raw Box::leak Rc::new Rc::clone Rc::strong_count Rc::try_unwrap Rc::downgrade Arc::new Arc::clone Arc::strong_count Arc::try_unwrap Arc::downgrade Weak::upgrade RefCell::new Cell::new Vec::with_capacity .reserve .shrink_to_fit .set_len .as_ptr .as_mut_ptr mem::swap mem::replace mem::take mem::drop mem::forget mem::size_of mem::align_of mem::transmute mem::zeroed mem::MaybeUninit::uninit MaybeUninit::uninit ptr::read ptr::write ptr::copy ptr::copy_nonoverlapping ptr::null ptr::null_mut ptr::drop_in_place ptr::swap alloc::alloc alloc::dealloc alloc::realloc alloc::alloc_zeroed Layout::new Layout::from_size_align slice::from_raw_parts slice::from_raw_parts_mut String::from_raw_parts Vec::from_raw_parts NonNull::new NonNull::dangling .into_raw .from_raw .borrow .borrow_mut .try_borrow .try_borrow_mut .get_mut .into_inner drop')
add('concurrency', 'rust', 'thread::spawn thread::sleep thread::yield_now thread::current thread::park thread::scope thread::Builder::new thread::available_parallelism .join .unpark .lock .try_lock .read .write .try_read .try_write .wait .wait_while .wait_timeout .notify_one .notify_all .send .recv .try_recv .recv_timeout .iter .try_iter Mutex::new RwLock::new Condvar::new Barrier::new Once::new OnceLock::new LazyLock::new OnceCell::new Arc::new mpsc::channel mpsc::sync_channel mpsc::Sender::send atomic::fence AtomicBool::new AtomicUsize::new AtomicI32::new AtomicU64::new .load .store .fetch_add .fetch_sub .fetch_and .fetch_or .fetch_xor .fetch_max .fetch_min .compare_exchange .compare_exchange_weak .swap .call_once tokio::spawn tokio::task::spawn tokio::task::spawn_blocking tokio::task::block_in_place tokio::runtime::Runtime::new tokio::runtime::Builder::new_multi_thread tokio::runtime::Builder::new_current_thread tokio::time::sleep tokio::time::timeout tokio::time::interval tokio::select! tokio::join! tokio::try_join! tokio::sync::mpsc::channel tokio::sync::oneshot::channel tokio::sync::broadcast::channel tokio::sync::watch::channel tokio::sync::Mutex::new tokio::sync::RwLock::new tokio::sync::Semaphore::new .acquire .acquire_owned .add_permits .await async_std::task::spawn rayon::join rayon::scope rayon::spawn .par_iter .par_iter_mut .into_par_iter .par_bridge .par_chunks crossbeam::scope crossbeam::channel::unbounded crossbeam::channel::bounded futures::executor::block_on futures::join! futures::select! futures::future::join_all .block_on .enter .abort .is_finished')
add('time_date', 'rust', 'Instant::now SystemTime::now Duration::from_secs Duration::from_millis Duration::from_micros Duration::from_nanos Duration::from_secs_f64 Duration::new .elapsed .duration_since .checked_add .checked_sub .as_secs .as_millis .as_micros .as_nanos .as_secs_f64 UNIX_EPOCH chrono::Utc::now chrono::Local::now Utc::now Local::now DateTime::parse_from_rfc3339 DateTime::parse_from_str NaiveDateTime::parse_from_str NaiveDate::from_ymd_opt .format .timestamp .timestamp_millis .with_timezone .naive_utc time::OffsetDateTime::now_utc OffsetDateTime::now_utc')
add('crypto_security', 'rust', 'rand::thread_rng rand::random rand::rngs::OsRng OsRng thread_rng .gen .gen_range .gen_bool .sample .fill_bytes .shuffle .choose getrandom::getrandom Sha256::new Sha256::digest Sha512::digest Sha1::new Md5::new md5::compute sha2::Sha256::digest .update .finalize .finalize_reset hmac::Hmac::new_from_slice Hmac::new_from_slice .verify_slice aes::Aes128::new aes_gcm::Aes256Gcm::new Aes256Gcm::new .encrypt .decrypt chacha20poly1305::ChaCha20Poly1305::new ring::digest::digest ring::hmac::sign ring::rand::SystemRandom::new ring::signature::Ed25519KeyPair::from_pkcs8 ed25519_dalek::SigningKey::generate rsa::RsaPrivateKey::new RsaPrivateKey::new openssl::ssl::SslConnector::builder rustls::ClientConfig::builder native_tls::TlsConnector::new argon2::Argon2::default bcrypt::hash bcrypt::verify scrypt::scrypt pbkdf2::pbkdf2_hmac jsonwebtoken::encode jsonwebtoken::decode base64::encode base64::decode zeroize::Zeroize::zeroize .zeroize subtle::ConstantTimeEq::ct_eq .ct_eq')
add('nonlocal_control_flow', 'rust', 'panic! unreachable! unimplemented! todo! assert! assert_eq! assert_ne! debug_assert! debug_assert_eq! debug_assert_ne! panic::catch_unwind panic::resume_unwind panic::set_hook panic::take_hook panic::panic_any std::panic::catch_unwind std::process::exit .unwrap .expect .unwrap_or .unwrap_or_else .unwrap_or_default .unwrap_err .expect_err .ok_or .ok_or_else .map_err .and_then .or_else .context .with_context anyhow! bail! ensure! Error::new Error::other')
add('reflection_metaprogramming', 'rust', 'Any::type_id TypeId::of type_name any::type_name any::type_name_of_val .downcast_ref .downcast_mut .downcast .is .type_id mem::discriminant include_str! include_bytes! include! concat! stringify! line! file! column! module_path! cfg! env! option_env! compile_error! macro_rules! std::any::type_name Box::<dyn Any>::downcast libloading::Library::new libloading::Library::get dlopen::raw::Library::open')
add('database_access', 'rust', 'rusqlite::Connection::open Connection::open Connection::open_in_memory .prepare .execute .query_row .query_map .query .execute_batch .last_insert_rowid .transaction .commit .rollback sqlx::query sqlx::query_as sqlx::query_scalar sqlx::query! sqlx::query_as! PgPool::connect SqlitePool::connect MySqlPool::connect sqlx::postgres::PgPoolOptions::new .fetch_one .fetch_all .fetch_optional .fetch diesel::insert_into diesel::update diesel::delete diesel::sql_query .load .get_result .get_results .first sea_orm::Database::connect postgres::Client::connect tokio_postgres::connect mysql::Pool::new redis::Client::open .get_connection .get_async_connection mongodb::Client::with_uri_str rocksdb::DB::open sled::open')
add('archive_compression', 'rust', 'flate2::read::GzDecoder::new flate2::write::GzEncoder::new GzDecoder::new GzEncoder::new ZlibEncoder::new ZlibDecoder::new DeflateEncoder::new tar::Archive::new tar::Builder::new Archive::new Builder::new .unpack .append_dir_all .append_file .entries .append_data zip::ZipArchive::new zip::ZipWriter::new ZipArchive::new ZipWriter::new .by_index .by_name .start_file .add_directory .extract bzip2::read::BzDecoder::new xz2::read::XzDecoder::new zstd::encode_all zstd::decode_all zstd::stream::Encoder::new lz4_flex::compress lz4_flex::decompress brotli::CompressorWriter::new snap::raw::Encoder::new miniz_oxide::deflate::compress_to_vec')
add('user_kernel_boundary', 'rust', 'libc::syscall libc::read libc::write libc::open libc::close libc::mmap libc::munmap libc::ioctl libc::fork libc::execve libc::kill libc::socket libc::bind libc::listen libc::accept libc::connect libc::getpid libc::mprotect nix::unistd::fork nix::unistd::read nix::unistd::write nix::sys::mman::mmap nix::sys::signal::kill nix::sys::signal::sigaction nix::sys::socket::socket nix::ioctl_read! nix::ioctl_write_ptr! nix::mount::mount rustix::fs::open rustix::io::read io_uring::IoUring::new windows_sys::Win32::System::Threading::CreateProcessW winapi::um::fileapi::CreateFileW')
add('low_level_hardware', 'rust', 'ptr::read_volatile ptr::write_volatile read_volatile write_volatile asm! global_asm! core::arch::asm! core::arch::x86_64::_mm_pause core::arch::x86_64::_rdtsc core::arch::x86_64::__cpuid core::hint::spin_loop hint::spin_loop hint::black_box hint::unreachable_unchecked core::arch::x86_64::_mm_prefetch core::arch::x86_64::_mm_mfence core::arch::x86_64::_mm_sfence core::arch::x86_64::_mm_lfence cortex_m::asm::nop cortex_m::asm::wfi cortex_m::asm::dsb cortex_m::asm::isb cortex_m::interrupt::free cortex_m::peripheral::Peripherals::take Peripherals::take volatile_register::RW::read volatile_register::RW::write embedded_hal::digital::OutputPin::set_high .set_high .set_low .toggle .is_high .is_low x86_64::instructions::port::Port::new .port_read .port_write')
add('simd_vector', 'rust', 'core::arch::x86_64::_mm_add_ps core::arch::x86_64::_mm256_add_ps core::arch::x86_64::_mm256_load_ps core::arch::x86_64::_mm256_store_ps core::arch::x86_64::_mm_loadu_si128 core::arch::x86_64::_mm256_loadu_si256 core::arch::x86_64::_mm512_add_ps core::arch::aarch64::vaddq_f32 core::arch::aarch64::vld1q_f32 core::simd::Simd::splat Simd::splat Simd::from_array Simd::from_slice .reduce_sum .reduce_max .reduce_min .simd_eq .simd_lt .simd_gt .to_array wide::f32x8::new packed_simd::f32x4::new')
add('gpu_compute', 'rust', 'wgpu::Instance::new wgpu::Instance::default .request_adapter .request_device .create_buffer .create_buffer_init .create_shader_module .create_compute_pipeline .create_render_pipeline .create_bind_group .create_command_encoder .begin_compute_pass .begin_render_pass .dispatch_workgroups .submit .write_buffer .map_async .create_texture .create_sampler vulkano::instance::Instance::new ash::Entry::load .create_instance .create_device .cmd_dispatch .cmd_draw cudarc::driver::CudaDevice::new .htod_copy .dtoh_sync_copy .alloc_zeros .launch ocl::Queue::new opencl3::context::Context::from_device')
add('graphics_rendering', 'rust', 'glutin::ContextBuilder::new gl::Clear gl::DrawArrays gl::DrawElements gl::BindVertexArray gl::BindBuffer gl::BufferData gl::GenBuffers gl::GenVertexArrays gl::CreateShader gl::ShaderSource gl::CompileShader gl::CreateProgram gl::LinkProgram gl::UseProgram gl::Viewport gl::ClearColor gl::Enable gl::TexImage2D gl::GenTextures glow::Context::from_loader_function bevy::prelude::App::new App::new .add_plugins .add_systems .insert_resource .run macroquad::prelude::clear_background draw_rectangle draw_circle draw_text draw_texture next_frame ggez::event::run piston_window::PistonWindow::new image::open image::load_from_memory image::ImageBuffer::new .save .to_rgba8 .resize .put_pixel skia_safe::Surface::new_raster_n32_premul tiny_skia::Pixmap::new')
add('gui_toolkit', 'rust', 'egui::CentralPanel::default eframe::run_native .add_button .add_label gtk::Application::new gtk::Window::new gtk::Button::with_label gtk::Box::new .connect_clicked .connect_activate .present .show_all iced::Application::run iced::widget::button slint::slint! slint::ComponentHandle::run druid::AppLauncher::with_window fltk::app::App::default tauri::Builder::default winit::event_loop::EventLoop::new .run_app WindowBuilder::new Window::new')
add('event_handling', 'rust', '.connect_clicked .connect_changed .connect_activate .connect_destroy .connect_key_press_event .connect_button_press_event .on_click .on_event .add_listener .add_event_listener .remove_event_listener .set_handler winit::event_loop::EventLoop::run_app EventLoop::run_app .poll_event .wait_event .next_event .subscribe .listen .emit .on')
add('data_structures_algorithms', 'rust', 'Vec::new Vec::from HashMap::new HashMap::with_capacity HashSet::new BTreeMap::new BTreeSet::new VecDeque::new BinaryHeap::new LinkedList::new IndexMap::new .push .pop .push_back .push_front .pop_back .pop_front .swap_remove .entry .or_insert .or_insert_with .or_default .and_modify .retain .extend .extend_from_slice .truncate .drain .split_off .sort .sort_by .sort_by_key .sort_unstable .sort_unstable_by .sort_unstable_by_key .binary_search .binary_search_by .reverse .rotate_left .rotate_right .dedup .dedup_by_key .chunks .chunks_exact .windows .partition .group_by .chunk_by mem::swap cmp::Reverse')

# ======================= Go（標準函式庫與常見套件） =======================
add('file_io', 'go', 'os.Open os.OpenFile os.Create os.CreateTemp os.ReadFile os.WriteFile os.ReadDir os.Stat os.Lstat os.Truncate os.NewFile os.Pipe os.Stdin os.Stdout os.Stderr ioutil.ReadFile ioutil.WriteFile ioutil.ReadAll ioutil.ReadDir ioutil.TempFile ioutil.TempDir ioutil.Discard io.Copy io.CopyN io.CopyBuffer io.ReadAll io.ReadFull io.ReadAtLeast io.WriteString io.Pipe io.MultiReader io.MultiWriter io.TeeReader io.LimitReader io.NewSectionReader io.WriteString bufio.NewReader bufio.NewWriter bufio.NewScanner bufio.NewReaderSize bufio.NewWriterSize bufio.NewReadWriter .Read .ReadAt .ReadFrom .ReadString .ReadBytes .ReadLine .ReadRune .ReadByte .Write .WriteAt .WriteTo .WriteString .WriteByte .WriteRune .Seek .Sync .Truncate .Readdir .Readdirnames .Scan .Text .Bytes .Flush .Fd .Stat embed.FS.ReadFile fs.ReadFile fs.ReadDir fs.WalkDir fs.Stat fs.Glob afero.NewOsFs os.File.Close')
add('filesystem_management', 'go', 'os.Mkdir os.MkdirAll os.MkdirTemp os.Remove os.RemoveAll os.Rename os.Link os.Symlink os.Readlink os.Chmod os.Chown os.Lchown os.Chtimes os.Chdir os.Getwd os.TempDir os.UserHomeDir os.UserCacheDir os.UserConfigDir os.IsExist os.IsNotExist os.IsPermission os.SameFile filepath.Walk filepath.WalkDir filepath.Glob filepath.Abs filepath.Rel filepath.Join filepath.Split filepath.Dir filepath.Base filepath.Ext filepath.Clean filepath.EvalSymlinks filepath.Match filepath.IsAbs path.Join path.Base path.Dir path.Ext path.Clean syscall.Mount syscall.Unmount syscall.Statfs syscall.Chroot unix.Mount unix.Unmount unix.Statfs unix.Chroot unix.Flock syscall.Flock fsnotify.NewWatcher .Add .Remove .Events')
add('network_io', 'go', 'net.Dial net.DialTimeout net.DialTCP net.DialUDP net.DialUnix net.Listen net.ListenTCP net.ListenUDP net.ListenPacket net.ListenUnix net.LookupHost net.LookupIP net.LookupAddr net.LookupCNAME net.LookupMX net.LookupTXT net.LookupSRV net.ResolveTCPAddr net.ResolveUDPAddr net.ResolveIPAddr net.ParseIP net.ParseCIDR net.SplitHostPort net.JoinHostPort net.FileConn net.FileListener net.Pipe net.Interfaces net.InterfaceByName net.InterfaceAddrs http.Get http.Post http.PostForm http.Head http.NewRequest http.NewRequestWithContext http.ListenAndServe http.ListenAndServeTLS http.Serve http.ServeTLS http.Handle http.HandleFunc http.NewServeMux http.FileServer http.ServeFile http.ServeContent http.Redirect http.Error http.NotFound http.StripPrefix http.TimeoutHandler http.MaxBytesReader http.DefaultClient.Do http.DefaultClient.Get http.Client.Do http.Transport.RoundTrip httputil.NewSingleHostReverseProxy httputil.DumpRequest httputil.DumpResponse httptest.NewServer httptest.NewRecorder httptest.NewRequest rpc.Dial rpc.DialHTTP rpc.Register rpc.HandleHTTP rpc.Accept rpc.NewClient jsonrpc.Dial smtp.SendMail smtp.Dial tls.Dial tls.Listen tls.Server tls.Client tls.LoadX509KeyPair tls.X509KeyPair websocket.Dial websocket.Accept websocket.Upgrader.Upgrade grpc.Dial grpc.NewServer grpc.NewClient grpc.DialContext .Accept .AcceptTCP .Dial .DialContext .ServeHTTP .Do .RoundTrip .SetDeadline .SetReadDeadline .SetWriteDeadline .RemoteAddr .LocalAddr .CloseRead .CloseWrite .SetKeepAlive .SetNoDelay .ListenAndServe .Serve .Shutdown .ReadFromUDP .WriteToUDP .ReadFrom .WriteTo .Handle .HandleFunc gin.Default gin.New echo.New fiber.New mux.NewRouter chi.NewRouter')
add('process_exec', 'go', 'exec.Command exec.CommandContext exec.LookPath os.StartProcess os.FindProcess os.Exit syscall.Exec syscall.ForkExec syscall.StartProcess syscall.Kill unix.Exec unix.Kill .Run .Start .Output .CombinedOutput .Wait .StdinPipe .StdoutPipe .StderrPipe .Signal .Kill .Release .Pid .ProcessState .Env .Dir .ExtraFiles .SysProcAttr os.Getpid os.Getppid os.Getuid os.Geteuid os.Getgid os.Getegid os.Getgroups os.Hostname')
add('env_config_access', 'go', 'os.Getenv os.LookupEnv os.Setenv os.Unsetenv os.Clearenv os.Environ os.ExpandEnv os.Expand os.Args os.Executable os.Getpagesize flag.Parse flag.String flag.Int flag.Bool flag.Duration flag.Float64 flag.Uint flag.Int64 flag.Var flag.StringVar flag.IntVar flag.BoolVar flag.DurationVar flag.Args flag.Arg flag.NArg flag.NFlag flag.Usage flag.PrintDefaults flag.NewFlagSet pflag.String pflag.Parse cobra.Command viper.GetString viper.GetInt viper.GetBool viper.ReadInConfig viper.SetConfigFile viper.AutomaticEnv viper.BindEnv viper.Unmarshal envconfig.Process godotenv.Load godotenv.Overload runtime.GOOS runtime.GOARCH runtime.NumCPU runtime.Version runtime.GOMAXPROCS user.Current user.Lookup user.LookupId')
add('logging_output', 'go', 'fmt.Print fmt.Println fmt.Printf fmt.Fprint fmt.Fprintln fmt.Fprintf log.Print log.Println log.Printf log.Fatal log.Fatalf log.Fatalln log.Panic log.Panicf log.Panicln log.New log.SetOutput log.SetFlags log.SetPrefix log.Default slog.Info slog.Warn slog.Error slog.Debug slog.InfoContext slog.WarnContext slog.ErrorContext slog.DebugContext slog.Log slog.New slog.SetDefault slog.NewJSONHandler slog.NewTextHandler zap.NewProduction zap.NewDevelopment zap.L zap.S .Info .Warn .Error .Debug .Infof .Warnf .Errorf .Debugf .Infow .Warnw .Errorw .Debugw .Fatal .Fatalf .Panic .Panicf .Sugar .Sync logrus.Info logrus.Warn logrus.Error logrus.Debug logrus.WithFields logrus.SetLevel zerolog.New println print')
add('string_formatting', 'go', 'fmt.Sprint fmt.Sprintf fmt.Sprintln fmt.Sscan fmt.Sscanf fmt.Sscanln fmt.Scan fmt.Scanf fmt.Scanln fmt.Fscan fmt.Fscanf fmt.Fscanln fmt.Errorf fmt.Append fmt.Appendf fmt.Appendln strconv.Itoa strconv.Atoi strconv.ParseInt strconv.ParseUint strconv.ParseFloat strconv.ParseBool strconv.FormatInt strconv.FormatUint strconv.FormatFloat strconv.FormatBool strconv.Quote strconv.QuoteToASCII strconv.Unquote strconv.AppendInt strconv.AppendQuote strings.Split strings.SplitN strings.SplitAfter strings.Fields strings.FieldsFunc strings.Join strings.Contains strings.ContainsAny strings.ContainsRune strings.HasPrefix strings.HasSuffix strings.Index strings.IndexByte strings.IndexRune strings.IndexAny strings.LastIndex strings.Replace strings.ReplaceAll strings.Trim strings.TrimSpace strings.TrimLeft strings.TrimRight strings.TrimPrefix strings.TrimSuffix strings.TrimFunc strings.ToUpper strings.ToLower strings.ToTitle strings.Title strings.Repeat strings.Count strings.EqualFold strings.Compare strings.Map strings.NewReader strings.NewReplacer strings.Builder strings.Cut strings.CutPrefix strings.CutSuffix bytes.NewBuffer bytes.NewBufferString bytes.NewReader bytes.Split bytes.Join bytes.Contains bytes.Equal bytes.Compare bytes.TrimSpace bytes.ToUpper utf8.RuneCountInString utf8.RuneCount utf8.DecodeRuneInString utf8.DecodeRune utf8.EncodeRune utf8.ValidString utf8.Valid unicode.IsLetter unicode.IsDigit unicode.IsSpace unicode.IsUpper unicode.IsLower unicode.IsPunct unicode.ToUpper unicode.ToLower text/template.New template.New template.Must template.ParseFiles template.ParseGlob .Execute .ExecuteTemplate .Parse .Funcs .String .WriteString .Grow .Reset .Len .Cap')
add('structured_data_parsing', 'go', 'json.Marshal json.MarshalIndent json.Unmarshal json.NewDecoder json.NewEncoder json.Valid json.Compact json.Indent json.HTMLEscape .Decode .Encode .SetIndent .DisallowUnknownFields .UseNumber .More .Token xml.Marshal xml.MarshalIndent xml.Unmarshal xml.NewDecoder xml.NewEncoder csv.NewReader csv.NewWriter .ReadAll .Comma .Comment gob.NewEncoder gob.NewDecoder gob.Register yaml.Marshal yaml.Unmarshal yaml.NewDecoder yaml.NewEncoder toml.Unmarshal toml.Marshal toml.Decode toml.DecodeFile proto.Marshal proto.Unmarshal protojson.Marshal protojson.Unmarshal msgpack.Marshal msgpack.Unmarshal hex.EncodeToString hex.DecodeString hex.Dump hex.Encode hex.Decode base64.StdEncoding.EncodeToString base64.StdEncoding.DecodeString base64.URLEncoding.EncodeToString base64.URLEncoding.DecodeString base64.RawStdEncoding.EncodeToString base64.RawURLEncoding.EncodeToString base32.StdEncoding.EncodeToString binary.Read binary.Write binary.Size binary.BigEndian.PutUint32 binary.BigEndian.Uint32 binary.LittleEndian.PutUint32 binary.LittleEndian.Uint32 binary.BigEndian.PutUint16 binary.LittleEndian.PutUint16 binary.BigEndian.PutUint64 binary.LittleEndian.PutUint64 binary.Uvarint binary.PutUvarint binary.Varint binary.PutVarint regexp.Compile regexp.MustCompile regexp.MatchString regexp.Match regexp.QuoteMeta regexp.CompilePOSIX regexp.MustCompilePOSIX .FindString .FindStringSubmatch .FindAllString .FindAllStringSubmatch .FindStringIndex .MatchString .ReplaceAllString .ReplaceAllStringFunc .ReplaceAll .SubexpNames .NumSubexp url.Parse url.ParseRequestURI url.QueryEscape url.QueryUnescape url.PathEscape url.PathUnescape url.ParseQuery url.Values.Encode .Query .Hostname .Port .String goquery.NewDocumentFromReader html.Parse html.EscapeString html.UnescapeString')
add('memory_management', 'go', 'make new append copy delete clear unsafe.Pointer unsafe.Sizeof unsafe.Alignof unsafe.Offsetof unsafe.Slice unsafe.SliceData unsafe.String unsafe.StringData unsafe.Add reflect.NewAt runtime.GC runtime.KeepAlive runtime.SetFinalizer runtime.ReadMemStats runtime.MemProfile runtime.NumGoroutine runtime.Stack runtime.Gosched debug.SetGCPercent debug.FreeOSMemory debug.SetMemoryLimit debug.ReadGCStats debug.PrintStack debug.Stack sync.Pool.Get sync.Pool.Put sync.Pool arena.NewArena mmap.Open syscall.Mmap syscall.Munmap syscall.Madvise syscall.Mlock syscall.Munlock unix.Mmap unix.Munmap unix.Madvise unix.Mlock unix.Munlock .Get .Put')
add('concurrency', 'go', 'sync.NewCond sync.OnceFunc sync.OnceValue sync.OnceValues atomic.AddInt32 atomic.AddInt64 atomic.AddUint32 atomic.AddUint64 atomic.LoadInt32 atomic.LoadInt64 atomic.LoadUint32 atomic.LoadUint64 atomic.LoadPointer atomic.StoreInt32 atomic.StoreInt64 atomic.StoreUint32 atomic.StoreUint64 atomic.StorePointer atomic.SwapInt32 atomic.SwapInt64 atomic.CompareAndSwapInt32 atomic.CompareAndSwapInt64 atomic.CompareAndSwapUint32 atomic.CompareAndSwapUint64 atomic.CompareAndSwapPointer atomic.Value context.Background context.TODO context.WithCancel context.WithTimeout context.WithDeadline context.WithValue context.WithCancelCause context.WithoutCancel context.AfterFunc context.Cause errgroup.WithContext semaphore.NewWeighted time.After time.AfterFunc time.Tick time.NewTimer time.NewTicker time.Sleep runtime.Gosched runtime.GOMAXPROCS runtime.NumGoroutine runtime.LockOSThread runtime.UnlockOSThread runtime.Goexit .Lock .Unlock .TryLock .RLock .RUnlock .TryRLock .RLocker .Wait .Add .Done .Go .Signal .Broadcast .Do .Load .Store .Swap .CompareAndSwap .LoadOrStore .LoadAndDelete .Range .Delete .Cancel .Done .Err .Deadline .Value .Stop .Reset .Acquire .TryAcquire .Release .SetLimit .TryGo .Stop gopool.Submit ants.NewPool .Submit .Invoke')
add('time_date', 'go', 'time.Now time.Since time.Until time.Unix time.UnixMilli time.UnixMicro time.Date time.Parse time.ParseInLocation time.ParseDuration time.LoadLocation time.FixedZone time.Duration .Format .AppendFormat .Add .AddDate .Sub .Before .After .Equal .Compare .Truncate .Round .Unix .UnixNano .UnixMilli .UnixMicro .In .UTC .Local .Location .Zone .Year .Month .Day .Hour .Minute .Second .Nanosecond .Weekday .YearDay .ISOWeek .IsZero .Seconds .Minutes .Hours .Milliseconds .Microseconds .Nanoseconds .Date .Clock syscall.Gettimeofday unix.ClockGettime unix.Nanosleep')
add('crypto_security', 'go', 'rand.Read rand.Int rand.Prime rand.Intn rand.Int31 rand.Int31n rand.Int63 rand.Int63n rand.Float32 rand.Float64 rand.Perm rand.Shuffle rand.Seed rand.New rand.NewSource rand.NewPCG rand.NewChaCha8 rand.N sha256.New sha256.Sum256 sha256.Sum224 sha512.New sha512.Sum512 sha1.New sha1.Sum md5.New md5.Sum sha3.New256 sha3.Sum256 blake2b.New256 blake2b.Sum256 hmac.New hmac.Equal subtle.ConstantTimeCompare subtle.ConstantTimeEq subtle.ConstantTimeSelect subtle.ConstantTimeCopy aes.NewCipher cipher.NewGCM cipher.NewCBCEncrypter cipher.NewCBCDecrypter cipher.NewCTR cipher.NewCFBEncrypter cipher.NewOFB cipher.NewStreamReader des.NewCipher rc4.NewCipher chacha20poly1305.New chacha20poly1305.NewX chacha20.NewUnauthenticatedCipher rsa.GenerateKey rsa.EncryptOAEP rsa.DecryptOAEP rsa.EncryptPKCS1v15 rsa.DecryptPKCS1v15 rsa.SignPKCS1v15 rsa.VerifyPKCS1v15 rsa.SignPSS rsa.VerifyPSS ecdsa.GenerateKey ecdsa.Sign ecdsa.SignASN1 ecdsa.Verify ecdsa.VerifyASN1 ecdh.P256 ed25519.GenerateKey ed25519.Sign ed25519.Verify elliptic.P256 elliptic.P384 x509.ParseCertificate x509.ParseCertificates x509.CreateCertificate x509.ParsePKCS1PrivateKey x509.ParsePKCS8PrivateKey x509.ParseECPrivateKey x509.MarshalPKCS8PrivateKey x509.MarshalPKIXPublicKey x509.NewCertPool x509.SystemCertPool pem.Decode pem.Encode pem.EncodeToMemory tls.LoadX509KeyPair tls.X509KeyPair tls.Config bcrypt.GenerateFromPassword bcrypt.CompareHashAndPassword scrypt.Key argon2.IDKey argon2.Key pbkdf2.Key hkdf.New hkdf.Extract hkdf.Expand jwt.NewWithClaims jwt.Parse jwt.ParseWithClaims jwt.New nacl.Seal nacl.Open secretbox.Seal secretbox.Open box.GenerateKey box.Seal box.Open ssh.NewClientConn ssh.Dial ssh.ParsePrivateKey ssh.NewSignerFromKey ssh.PublicKeys ssh.Password ssh.NewServerConn ssh.ParseAuthorizedKey ssh.MarshalAuthorizedKey crc32.ChecksumIEEE crc32.NewIEEE crc32.MakeTable crc32.Checksum crc64.New adler32.Checksum fnv.New32 fnv.New32a fnv.New64 fnv.New64a maphash.String maphash.Bytes .Sum .Sum256 .Seal .Open .Encrypt .Decrypt .Public .Sign .Verify .Generate .Sum32 .Sum64')
add('nonlocal_control_flow', 'go', 'panic recover runtime.Goexit runtime.Gosched os.Exit log.Fatal log.Fatalf log.Fatalln log.Panic log.Panicf log.Panicln errors.New errors.Is errors.As errors.Unwrap errors.Join fmt.Errorf debug.PrintStack debug.Stack debug.SetPanicOnFault debug.SetTraceback pkg/errors.Wrap errors.Wrap errors.Wrapf errors.WithStack errors.Cause errors.WithMessage')
add('reflection_metaprogramming', 'go', 'reflect.TypeOf reflect.ValueOf reflect.New reflect.NewAt reflect.Zero reflect.Indirect reflect.MakeSlice reflect.MakeMap reflect.MakeMapWithSize reflect.MakeChan reflect.MakeFunc reflect.Append reflect.AppendSlice reflect.Copy reflect.DeepEqual reflect.Swapper reflect.PtrTo reflect.PointerTo reflect.SliceOf reflect.MapOf reflect.ChanOf reflect.FuncOf reflect.ArrayOf reflect.StructOf reflect.Select reflect.VisibleFields reflect.TypeFor .Elem .Kind .NumField .Field .FieldByName .FieldByIndex .NumMethod .Method .MethodByName .Call .CallSlice .Interface .Set .SetInt .SetString .SetFloat .SetBool .SetBytes .SetMapIndex .SetLen .SetCap .Addr .CanSet .CanAddr .CanInterface .IsNil .IsValid .IsZero .MapKeys .MapIndex .MapRange .Len .Index .Slice .Tag .Get .Lookup .Name .PkgPath .String .Implements .AssignableTo .ConvertibleTo .Convert .Type runtime.Caller runtime.Callers runtime.FuncForPC runtime.CallersFrames .FileLine .Entry plugin.Open .Lookup go/parser.ParseFile parser.ParseFile parser.ParseExpr parser.ParseDir ast.Inspect ast.Walk ast.Print token.NewFileSet types.Config.Check importer.Default build.Import build.ImportDir')
add('database_access', 'go', 'sql.Open sql.OpenDB sql.Register sql.Drivers sql.Named sql.NullString sql.NullInt64 .Ping .PingContext .Query .QueryContext .QueryRow .QueryRowContext .Exec .ExecContext .Prepare .PrepareContext .Begin .BeginTx .Commit .Rollback .Next .Scan .Rows .Err .Columns .ColumnTypes .NextResultSet .LastInsertId .RowsAffected .SetMaxOpenConns .SetMaxIdleConns .SetConnMaxLifetime .SetConnMaxIdleTime .Conn .Stats sqlx.Open sqlx.Connect sqlx.MustConnect sqlx.MustOpen sqlx.In sqlx.Named .Get .Select .NamedExec .NamedQuery .Queryx .QueryRowx .Preparex .MustExec .Beginx gorm.Open .AutoMigrate .Create .Save .First .Find .Where .Delete .Updates .Update .Model .Table .Preload .Joins .Order .Limit .Offset .Raw .Count .Pluck .Transaction mongo.Connect mongo.NewClient .Database .Collection .InsertOne .InsertMany .FindOne .UpdateOne .UpdateMany .DeleteOne .DeleteMany .Aggregate .CountDocuments .Distinct .BulkWrite redis.NewClient redis.NewClusterClient redis.ParseURL .Set .SetNX .SetEX .GetSet .Incr .Decr .HSet .HGet .HGetAll .LPush .RPush .LPop .RPop .SAdd .SMembers .ZAdd .ZRange .Expire .TTL .Publish .Subscribe .Pipeline .TxPipeline .Watch .Eval .EvalSha pgx.Connect pgxpool.New pgxpool.NewWithConfig bolt.Open badger.Open leveldb.OpenFile pebble.Open sqlite3.Open etcd.New clientv3.New')
add('archive_compression', 'go', 'gzip.NewReader gzip.NewWriter gzip.NewWriterLevel zlib.NewReader zlib.NewWriter zlib.NewWriterLevel flate.NewReader flate.NewWriter lzw.NewReader lzw.NewWriter bzip2.NewReader tar.NewReader tar.NewWriter zip.NewReader zip.NewWriter zip.OpenReader zip.FileInfoHeader tar.FileInfoHeader .WriteHeader .Next .Create .CreateHeader .Open .Extract .Close .Flush zstd.NewReader zstd.NewWriter zstd.EncodeAll zstd.DecodeAll snappy.Encode snappy.Decode snappy.NewReader snappy.NewWriter lz4.NewReader lz4.NewWriter xz.NewReader xz.NewWriter brotli.NewReader brotli.NewWriter archiver.Archive archiver.Unarchive')
add('ipc', 'go', 'syscall.Pipe syscall.Socketpair unix.Pipe unix.Socketpair syscall.Shmget unix.Shmget syscall.Mmap os.Pipe net.Pipe signal.Notify signal.NotifyContext signal.Ignore signal.Reset signal.Stop syscall.Kill unix.Kill syscall.SIGINT syscall.SIGTERM')
add('user_kernel_boundary', 'go', 'syscall.Syscall syscall.Syscall6 syscall.RawSyscall syscall.RawSyscall6 syscall.Read syscall.Write syscall.Open syscall.Close syscall.Ioctl syscall.Socket syscall.Bind syscall.Listen syscall.Accept syscall.Connect syscall.Getpid syscall.Mprotect syscall.Ptrace syscall.Reboot syscall.Sethostname syscall.Setuid syscall.Setgid syscall.Setrlimit syscall.Getrlimit syscall.Prctl syscall.Unshare syscall.Setns unix.Syscall unix.Syscall6 unix.RawSyscall unix.Read unix.Write unix.Open unix.Close unix.Ioctl unix.IoctlSetInt unix.IoctlGetInt unix.Socket unix.Bind unix.Listen unix.Accept unix.Connect unix.Mprotect unix.Ptrace unix.Reboot unix.Sethostname unix.Setuid unix.Setgid unix.Setrlimit unix.Getrlimit unix.Prctl unix.Unshare unix.Setns unix.EpollCreate1 unix.EpollCtl unix.EpollWait unix.Select unix.Poll unix.Sendfile unix.Splice unix.Seccomp unix.Capget unix.Capset unix.Prlimit unix.Getrandom unix.Uname unix.Sysinfo windows.CreateFile windows.CreateProcess windows.OpenProcess windows.VirtualAlloc windows.VirtualProtect windows.LoadLibrary windows.GetProcAddress windows.NewLazySystemDLL windows.NewLazyDLL windows.NewProc .Call .Find .Addr .Load')
add('low_level_hardware', 'go', 'cpu.Initialize cpu.X86.HasAVX2 cpu.X86.HasAES cpu.X86.HasSSE42 cpu.ARM64.HasAES atomic.Pointer asm unsafe.Pointer runtime.KeepAlive syscall.Mmap periph.Init gpioreg.ByName rpio.Open rpio.Pin .Output .Input .High .Low .Toggle .Read .Write i2c.Open spi.Open serial.Open .SetSpeed .SetMode .Tx')
add('gui_toolkit', 'go', 'fyne.NewApp app.New app.NewWithID .NewWindow .SetContent .ShowAndRun .Show .Resize .SetMainMenu widget.NewButton widget.NewLabel widget.NewEntry widget.NewCheck widget.NewSelect widget.NewList widget.NewTable widget.NewProgressBar container.NewVBox container.NewHBox container.NewBorder container.NewTabs container.NewGridWithColumns dialog.ShowInformation dialog.ShowError dialog.ShowConfirm dialog.NewFileOpen dialog.ShowFileOpen walk.NewMainWindow walk.NewPushButton tview.NewApplication tview.NewBox tview.NewTextView tview.NewInputField tview.NewList tview.NewTable tview.NewFlex tview.NewButton tcell.NewScreen termui.Init termui.NewGrid bubbletea.NewProgram tea.NewProgram .Run .SetRoot .SetFocus .Draw .QueueUpdateDraw gtk.Init gtk.WindowNew gtk.ButtonNew gtk.LabelNew gtk.Main gtk.MainQuit gio.NewWindow ebiten.RunGame ebiten.SetWindowSize ebiten.NewImage .DrawImage .Fill .Update .Layout imgui.CreateContext imgui.NewFrame imgui.Render glfw.Init glfw.CreateWindow glfw.PollEvents .MakeContextCurrent .SwapBuffers .ShouldClose')
add('graphics_rendering', 'go', 'gl.Init gl.Clear gl.ClearColor gl.Enable gl.Disable gl.Viewport gl.GenBuffers gl.GenVertexArrays gl.BindBuffer gl.BindVertexArray gl.BufferData gl.CreateShader gl.ShaderSource gl.CompileShader gl.CreateProgram gl.AttachShader gl.LinkProgram gl.UseProgram gl.GetUniformLocation gl.Uniform1f gl.Uniform3f gl.UniformMatrix4fv gl.DrawArrays gl.DrawElements gl.TexImage2D gl.GenTextures gl.BindTexture gl.TexParameteri gl.ActiveTexture gl.VertexAttribPointer gl.EnableVertexAttribArray gl.Flush gl.Finish image.NewRGBA image.NewGray image.NewNRGBA image.NewYCbCr image.Decode image.DecodeConfig png.Decode png.Encode jpeg.Decode jpeg.Encode gif.Decode gif.Encode gif.EncodeAll draw.Draw draw.DrawMask draw.CatmullRom.Scale draw.BiLinear.Scale color.RGBA color.NRGBA color.Gray imaging.Open imaging.Save imaging.Resize imaging.Fit imaging.Fill imaging.Blur imaging.Sharpen imaging.AdjustContrast imaging.Grayscale gg.NewContext .DrawCircle .DrawRectangle .DrawLine .DrawString .SetRGB .SetHexColor .SetLineWidth .Fill .Stroke .Clear .SavePNG .LoadFontFace .DrawImage .Push .Pop .Translate .Rotate .Scale vulkan.Init wgpu.CreateInstance .RequestAdapter .RequestDevice .CreateBuffer .CreateTexture .CreateShaderModule .CreateRenderPipeline .CreateComputePipeline .CreateCommandEncoder .BeginRenderPass .BeginComputePass .Submit')
add('event_handling', 'go', 'signal.Notify signal.NotifyContext fsnotify.NewWatcher .Events .Errors .OnClick .OnChanged .OnSubmitted .OnDestroy .AddEventListener .RemoveEventListener .Subscribe .Unsubscribe .Publish .Emit .On .Off .Once .Trigger .Handle .HandleFunc .SetInputCapture .SetDoneFunc .SetChangedFunc .SetSelectedFunc .SetFocusFunc .SetBlurFunc .SetMouseCapture .SetBeforeDrawFunc .SetAfterDrawFunc .Watch .Notify .Listen .Wait .Poll .PollEvent .PostEvent .Dispatch .Bind .Connect .HandleEvent inotify.NewWatcher notify.Watch notify.Stop')
add('data_structures_algorithms', 'go', 'len cap min max clear close sort.Ints sort.Strings sort.Float64s sort.Slice sort.SliceStable sort.Sort sort.Stable sort.Search sort.SearchInts sort.SearchStrings sort.SearchFloat64s sort.IsSorted sort.SliceIsSorted sort.IntsAreSorted sort.StringsAreSorted sort.Reverse sort.NewIntSlice sort.NewStringSlice slices.Sort slices.SortFunc slices.SortStableFunc slices.IsSorted slices.IsSortedFunc slices.BinarySearch slices.BinarySearchFunc slices.Contains slices.ContainsFunc slices.Index slices.IndexFunc slices.Insert slices.Delete slices.DeleteFunc slices.Replace slices.Reverse slices.Max slices.MaxFunc slices.Min slices.MinFunc slices.Equal slices.EqualFunc slices.Compare slices.CompareFunc slices.Compact slices.CompactFunc slices.Clone slices.Concat slices.Grow slices.Clip slices.Repeat slices.Chunk slices.Collect slices.Sorted slices.Values slices.All slices.Backward maps.Keys maps.Values maps.Clone maps.Copy maps.Equal maps.EqualFunc maps.DeleteFunc maps.Insert maps.Collect maps.All cmp.Compare cmp.Less cmp.Or list.New ring.New heap.Init heap.Push heap.Pop heap.Remove heap.Fix .PushBack .PushFront .PopFront .Remove .InsertBefore .InsertAfter .MoveToFront .MoveToBack .MoveBefore .MoveAfter .Front .Back .Next .Prev .Len .Init .Do .Move .Link .Unlink .Push .Pop .Fix .Swap .Less utils.Contains lo.Map lo.Filter lo.Reduce lo.Uniq lo.GroupBy lo.Chunk lo.Flatten lo.Reverse lo.Shuffle lo.Contains lo.Find lo.Keys lo.Values lo.Must lo.Ternary')

# ======================= 類別的說明（新增的類別） =======================
NEW_CATEGORIES = {
    'data_structures_algorithms': {
        'label': 'Collections / algorithms',
        'description': 'Container operations and generic algorithms (C++ STL containers/<algorithm>, Rust Vec/HashMap/iterator adapters, Go slices/maps/sort/container packages). Pure in-memory data manipulation - no I/O, no side effects outside the data structure.',
    },
}

# ======================= API 語意（呼叫的引數與回傳值意義） =======================
def api(summary, params=None, ret=None, rules=None):
    d = {'summary': summary}
    d['parameters'] = [{'name': n, 'meaning': m} for n, m in (params or [])]
    if ret or rules:
        d['return'] = {'meaning': ret or ''}
        if rules:
            d['return']['rules'] = [{'when': {'op': o, 'value': v}, 'meaning': m} for o, v, m in rules]
    return d

API = {'cpp': {}, 'rust': {}, 'go': {}}
A = API['cpp']
A['make_shared'] = api('Allocates an object on the heap and returns a std::shared_ptr that owns it (one allocation for the object and its control block).', [('args', 'constructor arguments forwarded to the object type given in the template argument')], 'a shared_ptr (reference-counted owner); throws std::bad_alloc if allocation fails')
A['make_unique'] = api('Allocates an object on the heap and returns a std::unique_ptr that is its sole owner.', [('args', 'constructor arguments forwarded to the object type given in the template argument')], 'a unique_ptr (exclusive owner, freed automatically); throws std::bad_alloc if allocation fails')
A['getline'] = api('Reads one line from an input stream (up to the delimiter) into a string.', [('stream', 'the input stream (std::cin, an ifstream, ...)'), ('str', 'string that receives the line, without the delimiter'), ('delim', 'optional delimiter character (default newline)')], 'the stream itself; converts to false when nothing could be read (end of input or error)')
A['stoi'] = api('Converts a string to int (std::stoi).', [('str', 'text to parse'), ('pos', 'optional: receives the index of the first unparsed character'), ('base', 'numeric base (default 10)')], 'the parsed int; throws std::invalid_argument if no digits, std::out_of_range if the value does not fit')
A['stol'] = api('Converts a string to long (std::stol).', [('str', 'text to parse'), ('pos', 'optional: receives the index of the first unparsed character'), ('base', 'numeric base (default 10)')], 'the parsed long; throws std::invalid_argument / std::out_of_range')
A['stod'] = api('Converts a string to double (std::stod).', [('str', 'text to parse'), ('pos', 'optional: receives the index of the first unparsed character')], 'the parsed double; throws std::invalid_argument / std::out_of_range')
A['to_string'] = api('Converts a number to its decimal text (std::to_string).', [('value', 'integer or floating-point value')], 'a std::string')
A['sort'] = api('Sorts the range [first, last) in place (not stable; O(n log n)).', [('first', 'iterator to the first element'), ('last', 'iterator one past the last element'), ('comp', 'optional comparison; default operator<')], 'nothing (the range is rearranged)')
A['stable_sort'] = api('Sorts the range [first, last) in place keeping the relative order of equal elements.', [('first', 'iterator to the first element'), ('last', 'iterator one past the last element'), ('comp', 'optional comparison; default operator<')], 'nothing (the range is rearranged)')
A['accumulate'] = api('Folds the range [first, last) into one value, starting from init (default operation is +).', [('first', 'iterator to the first element'), ('last', 'iterator one past the last element'), ('init', 'initial value; its TYPE decides the result type (watch int vs double)'), ('op', 'optional binary operation')], 'the accumulated value')
A['thread'] = api('Starts a new thread running the given callable immediately.', [('callable', 'function/lambda the new thread runs'), ('args', 'arguments copied (or moved) into the thread')], 'a std::thread handle; it MUST be join()ed or detach()ed before destruction, otherwise std::terminate is called')
A['join'] = api('Blocks until the thread (or jthread) finishes.', [], 'nothing; the thread is no longer joinable afterwards')
A['detach'] = api('Lets the thread run independently; it can no longer be joined.', [], 'nothing; the thread is no longer joinable (it must not touch objects that die first)')
A['lock'] = api('Locks the mutex (or locks several with deadlock avoidance when std::lock is used); blocks until acquired.', [], 'nothing; the caller now owns the lock and must unlock it (prefer lock_guard / scoped_lock)')
A['unlock'] = api('Releases a mutex the calling thread holds.', [], 'nothing; unlocking a mutex you do not own is undefined behavior')
A['wait'] = api('Blocks on a condition variable (or future) until notified / ready; the predicate overload re-checks the condition to survive spurious wakeups.', [('lock', 'a unique_lock holding the associated mutex (released while waiting)'), ('pred', 'optional predicate: stop waiting when it returns true')], 'nothing (future::wait) - for condition_variable the lock is held again on return')
A['wait_for'] = api('Waits with a timeout.', [('duration', 'maximum time to wait'), ('pred', 'optional predicate')], 'std::cv_status::timeout / no_timeout (without predicate), or the predicate value (with predicate); future::wait_for returns std::future_status')
A['notify_one'] = api('Wakes one thread waiting on the condition variable.', [], 'nothing')
A['notify_all'] = api('Wakes all threads waiting on the condition variable.', [], 'nothing')
A['async'] = api('Runs a callable asynchronously and returns a std::future for its result.', [('policy', 'optional launch policy: std::launch::async (new thread) or deferred (lazy, runs on get/wait)'), ('callable', 'function to run'), ('args', 'its arguments')], 'a std::future; the destructor of an async future BLOCKS until the task finishes')
A['now'] = api('Reads the current time point of a std::chrono clock (system_clock = wall clock, steady_clock = monotonic).', [], 'a time_point; subtract two time_points to get a duration')
A['sleep_for'] = api('Blocks the calling thread for at least the given duration.', [('duration', 'e.g. std::chrono::milliseconds(100)')], 'nothing')
A['push_back'] = api('Appends an element at the end of the container (copy or move); may reallocate and invalidate iterators/references.', [('value', 'element to append')], 'nothing')
A['emplace_back'] = api('Constructs an element in place at the end of the container; may reallocate and invalidate iterators/references.', [('args', 'constructor arguments for the new element')], 'a reference to the new element (C++17)')
A['regex_match'] = api('Checks whether the WHOLE string matches the regular expression.', [('str', 'text to test'), ('match', 'optional: receives the capture groups'), ('re', 'std::regex')], 'true if the entire input matches')
A['regex_search'] = api('Searches for a match of the regular expression ANYWHERE in the string.', [('str', 'text to search'), ('match', 'optional: receives the capture groups'), ('re', 'std::regex')], 'true if a match was found')
A['create_directories'] = api('Creates a directory and all missing parent directories (std::filesystem).', [('path', 'directory to create'), ('ec', 'optional error_code; without it failures throw filesystem_error')], 'true if a directory was created, false if it already existed')
A['remove_all'] = api('Recursively deletes a file or directory tree (std::filesystem). Destructive.', [('path', 'file or directory to delete'), ('ec', 'optional error_code')], 'the number of files and directories removed')
A['exists'] = api('Tests whether a file or directory exists (std::filesystem).', [('path', 'path to test'), ('ec', 'optional error_code')], 'true if it exists')
A['file_size'] = api('Returns the size of a regular file in bytes (std::filesystem).', [('path', 'file path'), ('ec', 'optional error_code')], 'size in bytes; throws filesystem_error if not a regular file (without ec)')
A['terminate'] = api('Immediately ends the program through the terminate handler (by default calls abort).', [], 'does not return')
A['dynamic_pointer_cast'] = api('Runtime-checked downcast of a shared_ptr to a derived type.', [('ptr', 'shared_ptr to a polymorphic base')], 'a shared_ptr to the derived type, or an empty shared_ptr if the object is not of that type')
A['any_cast'] = api('Extracts the value held by a std::any.', [('any', 'the std::any')], 'the stored value; the value overload throws std::bad_any_cast if the type does not match, the pointer overload returns nullptr')
A['visit'] = api('Calls the visitor with the value currently held by a std::variant.', [('visitor', 'callable accepting every alternative type'), ('variant', 'the std::variant')], 'whatever the visitor returns')

R = API['rust']
R['File::open'] = api('Opens an existing file for reading.', [('path', 'file path (anything AsRef<Path>)')], 'io::Result<File>: Ok(file) on success, Err(io::Error) if missing, not permitted, ...')
R['File::create'] = api('Creates a file for writing, TRUNCATING it if it already exists.', [('path', 'file path (anything AsRef<Path>)')], 'io::Result<File>')
R['fs::read_to_string'] = api('Reads a whole file into a String (UTF-8).', [('path', 'file path')], 'io::Result<String>; Err if the file is unreadable or not valid UTF-8')
R['fs::read'] = api('Reads a whole file into a Vec<u8>.', [('path', 'file path')], 'io::Result<Vec<u8>>')
R['fs::write'] = api('Writes bytes to a file, creating it or TRUNCATING an existing one.', [('path', 'file path'), ('contents', 'bytes or string to write')], 'io::Result<()>')
R['fs::remove_file'] = api('Deletes a file. Destructive.', [('path', 'file path')], 'io::Result<()>')
R['fs::remove_dir_all'] = api('Recursively deletes a directory tree. Destructive.', [('path', 'directory path')], 'io::Result<()>')
R['fs::create_dir_all'] = api('Creates a directory and all missing parents.', [('path', 'directory path')], 'io::Result<()>; Ok even if it already exists')
R['TcpStream::connect'] = api('Opens a TCP connection (blocks until connected or failed).', [('addr', 'anything ToSocketAddrs: "host:port", (ip, port), ...')], 'io::Result<TcpStream>')
R['TcpListener::bind'] = api('Binds a TCP listening socket.', [('addr', 'anything ToSocketAddrs, e.g. "0.0.0.0:8080"')], 'io::Result<TcpListener>; Err if the port is in use or not permitted')
R['thread::spawn'] = api('Starts a new OS thread running the closure.', [('f', 'closure to run; it must be Send + \'static, so it usually needs `move`')], 'JoinHandle<T>; join() returns Err if the thread panicked. Dropping the handle detaches the thread')
R['Command::new'] = api('Starts building an external command (nothing runs until spawn/output/status).', [('program', 'program to run (looked up in PATH)')], 'a Command builder; add .arg()/.args() then .spawn()/.output()/.status()')
R['env::var'] = api('Reads an environment variable.', [('key', 'variable name')], 'Result<String, VarError>: Err(NotPresent) if unset, Err(NotUnicode) if not valid UTF-8')
R['process::exit'] = api('Ends the whole process immediately with the exit code (destructors do NOT run).', [('code', 'exit status (0 = success)')], 'does not return')
R['Instant::now'] = api('Reads the monotonic clock (for measuring elapsed time, not wall-clock time).', [], 'an Instant; .elapsed() gives the Duration since')
R['SystemTime::now'] = api('Reads the wall clock.', [], 'a SystemTime; duration_since(UNIX_EPOCH) can fail if the clock went backwards')
R['Box::new'] = api('Allocates a value on the heap.', [('x', 'the value to move into the allocation')], 'a Box<T> owning it (freed when dropped)')
R['Arc::new'] = api('Allocates a value behind an atomically reference-counted pointer shared across threads.', [('data', 'the value to share')], 'an Arc<T>; clone it to share, the value is freed when the last Arc drops')
R['Mutex::new'] = api('Creates a mutex protecting a value.', [('t', 'the protected value')], 'a Mutex<T>; .lock() returns a guard (Err if another thread panicked while holding it - "poisoned")')
R['.lock'] = api('Locks a Mutex (blocks until acquired).', [], 'LockResult<MutexGuard<T>>: Err when the mutex is poisoned (a thread panicked while holding it); the guard unlocks on drop')
R['mpsc::channel'] = api('Creates an unbounded multi-producer single-consumer channel.', [], '(Sender<T>, Receiver<T>); send never blocks, recv blocks, both fail once the other side is dropped')
R['serde_json::from_str'] = api('Parses JSON text into a typed value.', [('s', 'JSON text')], 'Result<T, serde_json::Error>; Err on malformed JSON or a shape that does not match T')
R['serde_json::to_string'] = api('Serializes a value to compact JSON text.', [('value', 'any Serialize value')], 'Result<String, serde_json::Error>')
R['Regex::new'] = api('Compiles a regular expression.', [('re', 'pattern string')], 'Result<Regex, regex::Error>; Err for an invalid pattern')
R['.unwrap'] = api('Extracts the Ok/Some value, PANICKING (ending the thread) on Err/None.', [], 'the inner value; panics with the error/None otherwise')
R['.expect'] = api('Like unwrap but panics with the given message.', [('msg', 'text shown when it panics')], 'the inner value; panics otherwise')
R['panic!'] = api('Unwinds the current thread (or aborts, depending on the panic strategy) with a message.', [('msg', 'format string and arguments')], 'does not return')
R['println!'] = api('Prints a formatted line to standard output (locks stdout; panics if writing fails).', [('fmt', 'format string with {} placeholders'), ('args', 'values to format')], 'nothing')
R['eprintln!'] = api('Prints a formatted line to standard error.', [('fmt', 'format string with {} placeholders'), ('args', 'values to format')], 'nothing')
R['format!'] = api('Builds a String from a format string (does not print).', [('fmt', 'format string with {} placeholders'), ('args', 'values to format')], 'a String')
R['tokio::spawn'] = api('Spawns an async task onto the Tokio runtime.', [('future', 'the future to run (must be Send + \'static)')], 'a JoinHandle<T>; awaiting it gives Result<T, JoinError> (Err if the task panicked or was cancelled)')
R['tokio::time::sleep'] = api('Asynchronously waits for the duration (does not block the thread).', [('duration', 'how long to wait')], 'a future that completes after the duration')
R['rusqlite::Connection::open'] = api('Opens (or creates) a SQLite database file.', [('path', 'database file path')], 'Result<Connection>')

G = API['go']
G['os.Open'] = api('Opens a file READ-ONLY.', [('name', 'file path')], '(*os.File, error): error is non-nil if the file does not exist or cannot be opened; remember to Close() it')
G['os.Create'] = api('Creates or TRUNCATES a file and opens it for reading and writing.', [('name', 'file path')], '(*os.File, error)')
G['os.OpenFile'] = api('Opens a file with explicit flags and permissions.', [('name', 'file path'), ('flag', 'O_RDONLY/O_WRONLY/O_RDWR | O_APPEND | O_CREATE | O_TRUNC | O_EXCL'), ('perm', 'permission bits used when the file is created (before umask)')], '(*os.File, error)')
G['os.ReadFile'] = api('Reads a whole file into memory.', [('name', 'file path')], '([]byte, error)')
G['os.WriteFile'] = api('Writes data to a file, creating or TRUNCATING it.', [('name', 'file path'), ('data', 'bytes to write'), ('perm', 'permission bits used when the file is created')], 'error (nil on success)')
G['os.Remove'] = api('Deletes a file or an empty directory. Destructive.', [('name', 'path')], 'error (nil on success)')
G['os.RemoveAll'] = api('Recursively deletes a path. Destructive.', [('path', 'file or directory tree')], 'error (nil on success, also nil if the path does not exist)')
G['os.MkdirAll'] = api('Creates a directory and all missing parents.', [('path', 'directory path'), ('perm', 'permission bits for newly created directories')], 'error (nil on success, also nil if it already exists)')
G['os.Exit'] = api('Ends the process immediately with the status code (deferred functions do NOT run).', [('code', 'exit status (0 = success)')], 'does not return')
G['os.Getenv'] = api('Reads an environment variable.', [('key', 'variable name')], 'the value, or "" when unset (use LookupEnv to tell "unset" from "empty")')
G['os.LookupEnv'] = api('Reads an environment variable and reports whether it is set.', [('key', 'variable name')], '(value string, found bool)')
G['http.Get'] = api('Sends an HTTP GET using the default client (no timeout!).', [('url', 'request URL')], '(*http.Response, error): error only for transport failures - a 404/500 is a normal response; the caller must Close() resp.Body')
G['http.Post'] = api('Sends an HTTP POST using the default client (no timeout!).', [('url', 'request URL'), ('contentType', 'Content-Type header value'), ('body', 'io.Reader with the request body')], '(*http.Response, error); the caller must Close() resp.Body')
G['http.ListenAndServe'] = api('Starts an HTTP server and blocks serving requests.', [('addr', 'listen address, e.g. ":8080"'), ('handler', 'http.Handler; nil means http.DefaultServeMux')], 'error: always non-nil when it returns (the server stopped or could not bind)')
G['http.HandleFunc'] = api('Registers a handler function for a URL pattern on the default mux.', [('pattern', 'URL path pattern'), ('handler', 'func(http.ResponseWriter, *http.Request)')], 'nothing')
G['net.Dial'] = api('Opens a network connection (blocks until connected or failed).', [('network', '"tcp", "udp", "unix", ...'), ('address', '"host:port"')], '(net.Conn, error)')
G['net.Listen'] = api('Starts listening on a local address.', [('network', '"tcp", "unix", ...'), ('address', 'local address, e.g. ":8080"')], '(net.Listener, error); call Accept() in a loop')
G['exec.Command'] = api('Prepares an external command (nothing runs until Run/Start/Output).', [('name', 'program (looked up in PATH)'), ('arg', 'arguments, passed WITHOUT a shell')], '*exec.Cmd')
G['exec.CommandContext'] = api('Like exec.Command but the process is killed when the context ends.', [('ctx', 'context controlling the process lifetime'), ('name', 'program'), ('arg', 'arguments')], '*exec.Cmd')
G['json.Marshal'] = api('Encodes a value as JSON.', [('v', 'any value')], '([]byte, error): error for unsupported types (channels, funcs, cycles)')
G['json.Unmarshal'] = api('Decodes JSON into a value.', [('data', 'JSON bytes'), ('v', 'POINTER to the destination')], 'error: non-nil on malformed JSON or a type mismatch (the destination may be partly filled)')
G['sql.Open'] = api('Prepares a database handle - it does NOT connect yet.', [('driverName', 'registered driver, e.g. "postgres"'), ('dataSourceName', 'driver-specific connection string')], '(*sql.DB, error); call Ping() to verify the connection')
G['strconv.Atoi'] = api('Parses a decimal integer.', [('s', 'text to parse')], '(int, error): error is non-nil if the text is not a valid int or out of range')
G['strconv.ParseInt'] = api('Parses an integer in a given base and bit size.', [('s', 'text'), ('base', '0 = detect from prefix, else 2..36'), ('bitSize', '0, 8, 16, 32 or 64')], '(int64, error)')
G['time.Sleep'] = api('Pauses the current goroutine for at least the duration.', [('d', 'time.Duration')], 'nothing')
G['time.After'] = api('Returns a channel that receives the current time once after the duration (leaks the timer until it fires).', [('d', 'time.Duration')], '<-chan time.Time')
G['context.WithTimeout'] = api('Derives a context that is cancelled after the timeout.', [('parent', 'parent context'), ('timeout', 'time.Duration')], '(context.Context, cancel func()); ALWAYS call cancel (usually defer cancel()) to release resources')
G['context.WithCancel'] = api('Derives a cancellable context.', [('parent', 'parent context')], '(context.Context, cancel func()); call cancel to stop everything derived from it')
G['.Lock'] = api('Locks a sync.Mutex / RWMutex (blocks until acquired).', [], 'nothing; pair with Unlock, usually via defer')
G['.Unlock'] = api('Unlocks a sync.Mutex; unlocking an unlocked mutex is a fatal error.', [], 'nothing')
G['.Wait'] = api('Blocks until the sync.WaitGroup counter drops to zero (or until a sync.Cond is signalled, or until an exec.Cmd finishes).', [], 'nothing (WaitGroup/Cond) or error (exec.Cmd.Wait)')
G['.Done'] = api('Decrements the WaitGroup counter by one (call when a goroutine finishes; usually deferred).', [], 'nothing')
G['panic'] = api('Stops normal execution of the goroutine and unwinds, running deferred functions; crashes the program unless recovered.', [('v', 'any value describing the failure')], 'does not return')
G['recover'] = api('Stops a panic in progress (only effective inside a deferred function).', [], 'the value passed to panic, or nil if the goroutine was not panicking')
G['make'] = api('Allocates and initializes a slice, map or channel.', [('t', 'slice/map/chan type'), ('size', 'length (slice), capacity hint (map) or buffer size (chan)')], 'the initialized value (not a pointer)')
G['append'] = api('Appends elements to a slice; may allocate a new backing array.', [('s', 'the slice'), ('elems', 'elements to add')], 'the resulting slice - you MUST assign it back (s = append(s, x))')
G['copy'] = api('Copies elements between slices.', [('dst', 'destination slice'), ('src', 'source slice')], 'the number of elements copied (min of both lengths)')
G['log.Fatal'] = api('Prints to the standard logger, then ends the process with status 1 (deferred functions do NOT run).', [('v', 'values to print')], 'does not return')
G['fmt.Println'] = api('Prints values to standard output separated by spaces, with a newline.', [('a', 'values to print')], '(n int, err error) - usually ignored')
G['fmt.Printf'] = api('Prints formatted text to standard output.', [('format', 'format string (%d %s %v ...)'), ('a', 'values')], '(n int, err error) - usually ignored')
G['fmt.Sprintf'] = api('Builds a formatted string (does not print).', [('format', 'format string (%d %s %v ...)'), ('a', 'values')], 'the formatted string')
G['fmt.Errorf'] = api('Creates an error with a formatted message; %w wraps another error so errors.Is/As can see it.', [('format', 'format string'), ('a', 'values')], 'an error')
G['sort.Slice'] = api('Sorts a slice in place using a less function (not stable).', [('x', 'the slice'), ('less', 'func(i, j int) bool: true if element i must come before j')], 'nothing')
G['rand.Intn'] = api('Returns a pseudo-random int in [0, n) from math/rand (NOT cryptographically secure).', [('n', 'upper bound, must be > 0')], 'a non-negative int below n; panics if n <= 0')
G['rand.Read'] = api('Fills the slice with random bytes (crypto/rand is cryptographically secure; math/rand is not - check the import).', [('b', 'slice to fill')], '(n int, err error)')

CONTROL_FLOW = {
    'rust': {'branch': ['if_expression', 'match_expression', 'match_arm'], 'loop': ['for_expression', 'while_expression', 'loop_expression'], 'error_handling': ['try_expression']},
    'go': {'branch': ['if_statement', 'expression_switch_statement', 'type_switch_statement', 'select_statement'], 'loop': ['for_statement'], 'error_handling': ['defer_statement']},
}

out = {'version': 1, 'note': 'generated by scripts/gen-name-tables.py - edit the script, not this file',
       'categories': {}, 'api': API, 'control_flow_nodes': CONTROL_FLOW, 'structural_signals': {
           'async_await_usage': {'rust': ['await_expression', 'async_block'], 'go': []},
           'lambda_usage': {'rust': ['closure_expression'], 'go': ['func_literal'], 'cpp': ['lambda_expression']},
           'concurrency_construct': {'go': ['go_statement', 'select_statement'], 'rust': []}}}
for cat, langs in C.items():
    ent = {'languages': langs}
    if cat in NEW_CATEGORIES:
        ent.update(NEW_CATEGORIES[cat])
    out['categories'][cat] = ent

# 同一個名稱不能同時在兩個類別（引擎的查表是「後蓋前」，歸類會取決於類別順序）。自動處理：
#   - 以「.」開頭的方法名（任何接收者都會命中）出現在多個類別 → 太含糊，全部移除（寧可不分類也不要亂分類）
#   - 完整名稱（pkg.Func、a::b）重複 → 保留第一個登記的類別
dups = {}
for cat, langs in C.items():
    for l, ns in langs.items():
        for n in ns:
            dups.setdefault((l, n), []).append(cat)
removed_bare, removed_q = [], []
for (l, n), cs in dups.items():
    if len(cs) < 2:
        continue
    if n.startswith('.'):
        for c in cs:
            C[c][l].remove(n)
        removed_bare.append((l, n))
    else:
        for c in cs[1:]:
            C[c][l].remove(n)
        removed_q.append((l, n, cs[0]))
# 太泛用的方法名（任何型別都有同名方法）一律不分類：寧可留在「未分類」讓人看，也不要把 f.Close() 說成壓縮、把 path.join() 說成執行緒
DENY_BARE = {
    'go': set('.Close .Open .Create .Extract .Text .Bytes .Stat .Value .Stop .Store .Range .Cancel .Deadline .Name .Type .Index .Slice .Interface .Elem .Kind .Field .Method .IsNil .IsValid .Tag .Lookup .Convert .SetLen .SetCap .Entry .Select .Save .First .Where .Model .Table .Order .Limit .Offset .Raw .Count .Pluck .Transaction .Database .Collection .Conn .Stats .Rows .Columns .ColumnTypes .Begin .Pipeline .Distinct .Draw .Show .Resize .SetFocus .Layout .Clear .Scale .Translate .Rotate .Stroke .Sub .Before .After .Equal .Compare .Round .Unix .Year .Month .Day .Hour .Minute .Second .Date .Clock .Location .Zone .In .Local .Seconds .Minutes .Hours .Format .Parse .Grow .Cap .Info .Warn .Error .Debug .Fatal .Panic .Sugar .More .Token .ReadAll .Comma .Comment .Hostname .Port .Sum .Public .Generate .Start .Pid .ProcessState .Env .Dir .ExtraFiles .SysProcAttr .Input .High .Low .Toggle .SetSpeed .SetMode .Tx .Front .Back .Prev .Init .Move .Link .Unlink .Fix .Less .Put .Invoke .Acquire .Errors .Unsubscribe .Emit .On .Off .Once .Trigger .Notify .Listen .Poll .Dispatch .Bind .Connect .Serve .Fd'.split()),
    'rust': set('.bytes .flush .seek .metadata .parent .display .connect .get .post .put .delete .header .json .send_async .get_mut .into_inner .read .write .iter .store .swap .acquire .await .enter .abort .checked_add .checked_sub .format .trim .trim_start .trim_end .split .lines .chars .contains .starts_with .ends_with .replace .replacen .find .rfind .repeat .concat .push_str .as_str .into_bytes .eq_ignore_ascii_case .is_alphabetic .is_numeric .is_whitespace .to_string .to_owned .to_uppercase .to_lowercase .rsplit .init .ok_or .ok_or_else .map_err .and_then .or_else .context .with_context .unwrap_or .unwrap_or_else .unwrap_or_default .is .gen .sample .shuffle .choose .update .arg .args .envs .env .stdin .stdout .stderr .kill .id .status .execute .query .transaction .commit .rollback .fetch .first .prepare .entries .extract .toggle .is_high .is_low .to_array .submit .launch .run .save .resize .present .run_app .add_listener .set_handler .subscribe .listen .emit .on'.split()),
}
for l, deny in DENY_BARE.items():
    for cat in C:
        if l in C[cat]:
            C[cat][l] = [n for n in C[cat][l] if n not in deny]
print('移除含糊的方法名 %d 個（出現在多個類別）；完整名稱重複 %d 個（保留第一個類別）' % (len(removed_bare), len(removed_q)))

dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'renderer', 'src', 'behavior', 'names_cpp_rust_go.json')
with open(dest, 'w', encoding='utf-8') as f:
    json.dump(out, f, ensure_ascii=False, indent=1)
    f.write('\n')
tot = {}
for cat, langs in C.items():
    for l, ns in langs.items():
        tot[l] = tot.get(l, 0) + len(ns)
print('names:', tot, '| api:', {k: len(v) for k, v in API.items()})
